server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eBook
    username: postgres
    password: 123456

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        default_schema: public
  liquibase:
    enabled: false
  sql:
    init:
      mode: always

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
